package com.mcwbridges.kikoz.init;

import com.mcwbridges.kikoz.MacawsBridges;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class TabInit {
	
	public static final DeferredRegister<CreativeModeTab> CREATIVE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, MacawsBridges.MOD_ID);

	public static final RegistryObject<CreativeModeTab> BRIDGEITEMGROUP = CREATIVE_TABS.register("mcwbridges", () -> CreativeModeTab.builder()
			.title(Component.translatable("itemGroup." + MacawsBridges.MOD_ID))
			.icon(() -> new ItemStack(BlockInit.IRON_BRIDGE.get()))
			.displayItems((enabledFeatures, entries) -> {
				entries.accept(ItemInit.PLIERS.get());
				entries.accept(BlockInit.BRIDGE_TORCH.get());
				entries.accept(BlockInit.BRIDGE_LANTERN.get());
				entries.accept(BlockInit.IRON_BRIDGE.get());
				entries.accept(BlockInit.OAK_LOG_BRIDGE_MIDDLE.get());
				entries.accept(BlockInit.BIRCH_LOG_BRIDGE_MIDDLE.get());
				entries.accept(BlockInit.ACACIA_LOG_BRIDGE_MIDDLE.get());
				entries.accept(BlockInit.SPRUCE_LOG_BRIDGE_MIDDLE.get());
				entries.accept(BlockInit.JUNGLE_LOG_BRIDGE_MIDDLE.get());
				entries.accept(BlockInit.DARK_OAK_LOG_BRIDGE_MIDDLE.get());
				entries.accept(BlockInit.CRIMSON_LOG_BRIDGE_MIDDLE.get());
				entries.accept(BlockInit.WARPED_LOG_BRIDGE_MIDDLE.get());
				entries.accept(BlockInit.MANGROVE_LOG_BRIDGE_MIDDLE.get());
				entries.accept(BlockInit.CHERRY_LOG_BRIDGE_MIDDLE.get());
				entries.accept(BlockInit.ROPE_OAK_BRIDGE.get());
				entries.accept(BlockInit.ROPE_BIRCH_BRIDGE.get());
				entries.accept(BlockInit.ROPE_SPRUCE_BRIDGE.get());
				entries.accept(BlockInit.ROPE_JUNGLE_BRIDGE.get());
				entries.accept(BlockInit.ROPE_ACACIA_BRIDGE.get());
				entries.accept(BlockInit.ROPE_DARK_OAK_BRIDGE.get());
				entries.accept(BlockInit.ROPE_CRIMSON_BRIDGE.get());
				entries.accept(BlockInit.ROPE_WARPED_BRIDGE.get());
				entries.accept(BlockInit.ROPE_MANGROVE_BRIDGE.get());
				entries.accept(BlockInit.ROPE_CHERRY_BRIDGE.get());
				entries.accept(BlockInit.BRICK_BRIDGE.get());
				entries.accept(BlockInit.SANDSTONE_BRIDGE.get());
				entries.accept(BlockInit.STONE_BRICK_BRIDGE.get());
				entries.accept(BlockInit.ORANGE_SANDSTONE_BRIDGE.get());
				entries.accept(BlockInit.BLACKSTONE_BRIDGE.get());
				entries.accept(BlockInit.MOSSY_STONE_BRICK_BRIDGE.get());
				entries.accept(BlockInit.DEEPSLATE_BRICK_BRIDGE.get());
				entries.accept(BlockInit.DEEPSLATE_TILE_BRIDGE.get());
				entries.accept(BlockInit.MUD_BRICK_BRIDGE.get());
				entries.accept(BlockInit.COBBLESTONE_BRIDGE.get());
				entries.accept(BlockInit.MOSSY_COBBLESTONE_BRIDGE.get());
				entries.accept(BlockInit.ANDESITE_BRIDGE.get());
				entries.accept(BlockInit.GRANITE_BRIDGE.get());
				entries.accept(BlockInit.DIORITE_BRIDGE.get());
				entries.accept(BlockInit.PRISMARINE_BRICKS_BRIDGE.get());
				entries.accept(BlockInit.NETHER_BRICKS_BRIDGE.get());
				entries.accept(BlockInit.END_STONE_BRICKS_BRIDGE.get());
				entries.accept(BlockInit.OAK_RAIL_BRIDGE.get());
				entries.accept(BlockInit.SPRUCE_RAIL_BRIDGE.get());
				entries.accept(BlockInit.BIRCH_RAIL_BRIDGE.get());
				entries.accept(BlockInit.JUNGLE_RAIL_BRIDGE.get());
				entries.accept(BlockInit.ACACIA_RAIL_BRIDGE.get());
				entries.accept(BlockInit.DARK_OAK_RAIL_BRIDGE.get());
				entries.accept(BlockInit.CRIMSON_RAIL_BRIDGE.get());
				entries.accept(BlockInit.WARPED_RAIL_BRIDGE.get());
				entries.accept(BlockInit.MANGROVE_RAIL_BRIDGE.get());
				entries.accept(BlockInit.CHERRY_RAIL_BRIDGE.get());
				entries.accept(BlockInit.BAMBOO_BRIDGE.get());
				entries.accept(BlockInit.DRY_BAMBOO_BRIDGE.get());
				entries.accept(BlockInit.ASIAN_RED_BRIDGE.get());
				entries.accept(BlockInit.GLASS_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_STONE_BRICKS_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_SANDSTONE_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_BRICKS_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_ORANGE_SANDSTONE_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_BLACKSTONE_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_MOSSY_STONE_BRICKS_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_DEEPSLATE_BRICKS_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_DEEPSLATE_TILES_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_MUD_BRICKS_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_COBBLESTONE_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_MOSSY_COBBLESTONE_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_ANDESITE_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_GRANITE_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_DIORITE_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_PRISMARINE_BRICKS_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_NETHER_BRICKS_BRIDGE.get());
				entries.accept(BlockInit.BALUSTRADE_END_STONE_BRICKS_BRIDGE.get());
				entries.accept(BlockInit.IRON_BRIDGE_PIER.get());
				entries.accept(BlockInit.OAK_BRIDGE_PIER.get());
				entries.accept(BlockInit.SPRUCE_BRIDGE_PIER.get());
				entries.accept(BlockInit.BIRCH_BRIDGE_PIER.get());
				entries.accept(BlockInit.JUNGLE_BRIDGE_PIER.get());
				entries.accept(BlockInit.ACACIA_BRIDGE_PIER.get());
				entries.accept(BlockInit.DARK_OAK_BRIDGE_PIER.get());
				entries.accept(BlockInit.CRIMSON_BRIDGE_PIER.get());
				entries.accept(BlockInit.WARPED_BRIDGE_PIER.get());
				entries.accept(BlockInit.MANGROVE_BRIDGE_PIER.get());
				entries.accept(BlockInit.CHERRY_BRIDGE_PIER.get());
				entries.accept(BlockInit.ASIAN_RED_BRIDGE_PIER.get());	
				entries.accept(BlockInit.GLASS_BRIDGE_PIER.get());	
				entries.accept(BlockInit.BRICK_BRIDGE_PIER.get());
				entries.accept(BlockInit.SANDSTONE_BRIDGE_PIER.get());
				entries.accept(BlockInit.STONE_BRIDGE_PIER.get());
				entries.accept(BlockInit.RED_SANDSTONE_BRIDGE_PIER.get());
				entries.accept(BlockInit.BLACKSTONE_BRIDGE_PIER.get());
				entries.accept(BlockInit.MOSSY_STONE_BRIDGE_PIER.get());
				entries.accept(BlockInit.DEEPSLATE_BRICK_BRIDGE_PIER.get());
				entries.accept(BlockInit.DEEPSLATE_TILE_BRIDGE_PIER.get());
				entries.accept(BlockInit.MUD_BRICK_BRIDGE_PIER.get());
				entries.accept(BlockInit.BAMBOO_BRIDGE_PIER.get());
				entries.accept(BlockInit.DRY_BAMBOO_BRIDGE_PIER.get());
				entries.accept(BlockInit.COBBLESTONE_BRIDGE_PIER.get());
				entries.accept(BlockInit.MOSSY_COBBLESTONE_BRIDGE_PIER.get());
				entries.accept(BlockInit.ANDESITE_BRIDGE_PIER.get());
				entries.accept(BlockInit.GRANITE_BRIDGE_PIER.get());
				entries.accept(BlockInit.DIORITE_BRIDGE_PIER.get());
				entries.accept(BlockInit.PRISMARINE_BRICKS_BRIDGE_PIER.get());
				entries.accept(BlockInit.NETHER_BRICKS_BRIDGE_PIER.get());
				entries.accept(BlockInit.END_STONE_BRICKS_BRIDGE_PIER.get());
				entries.accept(BlockInit.IRON_BRIDGE_STAIR.get());
				entries.accept(BlockInit.OAK_LOG_BRIDGE_STAIR.get());
				entries.accept(BlockInit.SPRUCE_LOG_BRIDGE_STAIR.get());
				entries.accept(BlockInit.BIRCH_LOG_BRIDGE_STAIR.get());
				entries.accept(BlockInit.JUNGLE_LOG_BRIDGE_STAIR.get());
				entries.accept(BlockInit.ACACIA_LOG_BRIDGE_STAIR.get());
				entries.accept(BlockInit.DARK_OAK_LOG_BRIDGE_STAIR.get());
				entries.accept(BlockInit.CRIMSON_LOG_BRIDGE_STAIR.get());
				entries.accept(BlockInit.WARPED_LOG_BRIDGE_STAIR.get());
				entries.accept(BlockInit.MANGROVE_LOG_BRIDGE_STAIR.get());
				entries.accept(BlockInit.CHERRY_LOG_BRIDGE_STAIR.get());
				entries.accept(BlockInit.OAK_ROPE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.SPRUCE_ROPE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.BIRCH_ROPE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.JUNGLE_ROPE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.ACACIA_ROPE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.DARK_OAK_ROPE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.CRIMSON_ROPE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.WARPED_ROPE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.MANGROVE_ROPE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.CHERRY_ROPE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.STONE_BRICK_BRIDGE_STAIR.get());
				entries.accept(BlockInit.SANDSTONE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.ASIAN_RED_BRIDGE_STAIR.get());
				entries.accept(BlockInit.GLASS_BRIDGE_STAIR.get());
				entries.accept(BlockInit.BRICK_BRIDGE_STAIR.get());
				entries.accept(BlockInit.RED_SANDSTONE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.BLACKSTONE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.MOSSY_STONE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.DEEPSLATE_BRICK_BRIDGE_STAIR.get());
				entries.accept(BlockInit.DEEPSLATE_TILE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.MUD_BRICK_BRIDGE_STAIR.get());
				entries.accept(BlockInit.BAMBOO_BRIDGE_STAIR.get());
				entries.accept(BlockInit.DRY_BAMBOO_BRIDGE_STAIR.get());
				entries.accept(BlockInit.COBBLESTONE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.MOSSY_COBBLESTONE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.ANDESITE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.GRANITE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.DIORITE_BRIDGE_STAIR.get());
				entries.accept(BlockInit.PRISMARINE_BRICKS_BRIDGE_STAIR.get());
				entries.accept(BlockInit.NETHER_BRICKS_BRIDGE_STAIR.get());
				entries.accept(BlockInit.END_STONE_BRICKS_BRIDGE_STAIR.get());	
			})
			.build());
}
